# Site settings
url             : 'https://ahmetcadirci.com.tr'
baseurl         : '/'
google_analytics: 'UA-66383788-5'
disqus_shortname: 'ahmet25'


# Seo settings
title      : 'Ahmet Çadırcı'
description: 'Ahmet Çadırcı kişisel web sitemde blog yazıları, video, podcast vb. içerikler yer almaktadır. İletişim sayfasından bana ulaşabilirsiniz.'
author     : 'ahmetcadircicom'
lang       : 'tr-TR'
twitter:
  username: 'ahmetcadircicom'
  card    : summary
  creator : 'ahmetcadircicom'

facebook:
  app_id   : 
  publisher: 
  admins   : 

logo: '/images/favicons/apple-touch-icon-180x180.png'
webmaster_verifications:
  google: 6pGvTVBLD2qL0rZX53G1iQDrKrplHeh2a-glZ6SZVnE
  bing  : 6E7E1B4936C97BCAC726C753E0DDD914
  yandex: ec8ac6fb02cf0aae
  alexa : 
  baidu : 

social:
  name: Ahmet Çadırcı
  links:
    - https://github.com/ahmetcadirci25

author:
  name               : 'Ahmet Çadırcı'
  email              : ahmetcadirci25@gmail.com

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate   : 5
permalink  : /:year/:title/
markdown   : kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
        
plugins: ['jekyll-paginate', 'jekyll-sitemap', 'jekyll-seo-tag']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

# Podcast Listesi
ahmet-cadirci       :
  title             : "Podcast — Ahmet Çadırcı"
  subtitle          : "Podcast — Ahmet Çadırcı"
  link              : "https://ahmetcadirci.com.tr/podcast/"
  description       : "En güncel internet, teknoloji ve bilişim haberlerini podcast kayıtları üzerinden ulaşabilirsiniz."
  keywords          : "ahmet çadırcı, wordpress, podcast, teknoloji, internet"
  language          : "tr-tr"
  spotifycountry    : "tr"
  copyright         : "Ahmet Çadırcı"
  author            : "Ahmet Çadırcı"
  email             : "ahmetcadirci25@gmail.com"
  category          : "Technology"
  subcategory       : "Software How-To"
  image             : "https://ahmetcadirci.com.tr/images/ahmet-cadirci.jpg"
  explicit          : "clean"

gonul-sadasi        :
  title             : "Kemal Sayar & Sadettin Ökten — Gönül Sadası"
  subtitle          : "Kemal Sayar & Sadettin Ökten — Gönül Sadası"
  link              : "https://ahmetcadirci.com.tr/podcast/"
  description       : "Kemal Sayar ve Prof. Dr. Sadettin Ökten hoş sohbetleri..."
  keywords          : "kemal sayar, sadettin ökten, sohbet, islam, ahmet çadırcı"
  language          : "tr-tr"
  spotifycountry    : "tr"
  copyright         : "Ahmet Çadırcı"
  author            : "Ahmet Çadırcı"
  email             : "ahmetcadirci25@gmail.com"
  category          : "Religion &#38; Spirituality"
  subcategory       : "Islam"
  image             : "https://ahmetcadirci.com.tr/images/gonul-sadasi.jpg"
  explicit          : "clean"

can-veren-pervaneler: 
  title             : "Hayati İnanç & Selahaddin Kocaaslan — Can Veren Pervâneler"
  subtitle          : "Hayati İnanç & Selahaddin Kocaaslan — Can Veren Pervâneler"
  link              : "https://ahmetcadirci.com.tr/podcast/"
  description       : "Nâbi'den Şeyh Gâlib'e, Bâki'den Fuzûli'ye nice müstesna değerimizin en güzel şiirleri ile günümüze ve gönlümüze taşınacağı Hayati İnanç ve Selahaddin Kocaaslan ile 'Can Veren Pervâneler' programında..."
  keywords          : "hayati inanç, selahaddin kocaaslan, şiir, divan edebiyatı, divan şiiri, sohbet, islam, ahmet çadırcı"
  language          : "tr-tr"
  spotifycountry    : "tr"
  copyright         : "Ahmet Çadırcı"
  author            : "Ahmet Çadırcı"
  email             : "ahmetcadirci25@gmail.com"
  category          : "Religion &#38; Spirituality"
  subcategory       : "Islam"
  image             : "https://ahmetcadirci.com.tr/images/can-veren-pervaneler.jpg"
  explicit          : "clean"

genclerle-basbasa   :
  title             : "Sadettin Ökten — Gençlerle Başbaşa"
  subtitle          : "Sadettin Ökten — Gençlerle Başbaşa"
  link              : "https://ahmetcadirci.com.tr/podcast/"
  description       : "Prof. Dr. Sadettin Ökten ile Gençlerle Başbaşa Podcast Yayınları."
  keywords          : "sadettin ökten, ahlak, podcast, edebiyat, kültür, toplum, medeniyet, kültür, sanat, sohbet, islam, tasavvuf, tarikat, marifet, ahmet çadırcı"
  language          : "tr-tr"
  spotifycountry    : "tr"
  copyright         : "Ahmet Çadırcı"
  author            : "Ahmet Çadırcı"
  email             : "ahmetcadirci25@gmail.com"
  category          : "Religion &#38; Spirituality"
  subcategory       : "Islam"
  image             : "https://ahmetcadirci.com.tr/images/genclerle-basbasa.jpg"
  explicit          : "clean"